# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bullet',
            name='datemod',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='caliber',
            name='datemod',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='comment',
            name='datemod',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='loads',
            name='datemod',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='powder',
            name='datemod',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='test',
            name='datemod',
            field=models.DateTimeField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='caliber',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='loads',
            name='case',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='\u0141uska'),
        ),
        migrations.AlterField(
            model_name='loads',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='loads',
            name='prime',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Sp\u0142onka'),
        ),
        migrations.AlterField(
            model_name='powder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
